### ISSUE TITLE
Add "maxZoomLevel" option to accompany the "mapFitData" option

### ISSUE THREAD

**Issue by amotl** [hiveeyes/grafana-worldmap-panel#2]
@wetterfrosch told me the other day that the current ["mapFitData" implementation](https://community.hiveeyes.org/t/grafana-worldmap-panel-0-3-0-dev-series/1824/16) is nice but rather impracticable, so he asked

> Can we introduce another option like "maxZoomLevel" which accompanies the "mapFitData" option which would prevent the automatic fitting mechanics to select a bounding box which is too small?

**Comment by wetterfrosch** [comment]
In general I always wondered in other map tools, too, if there could be a strategy to establish a default zoom-level, which isn't either e.g. 6 and 7, but more like a "7 shrinked to a 6.5". but thats just for the philosophical aspect of this tissue.

**Comment by amotl** [comment]
Resolved by 416335fc.
